# see https://docs.searxng.org/admin/engines/settings.html#use-default-settings
use_default_settings: false

server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key : "KeyHere"
  limiter: false  # can be disabled for a private instance
  image_proxy: true
  default_http_headers:
    X-Content-Type-Options : nosniff
    X-XSS-Protection : 1; mode=block
    X-Download-Options : noopen
    X-Robots-Tag : noindex, nofollow
    Referrer-Policy : no-referrer

ui:
  static_use_hash: true
  default_locale: ""
  query_in_title: false
  infinite_scroll: true
  center_alignment: true
  default_theme: simple
  theme_args:
    simple_style: dark
  results_on_new_tab: true

redis:
  url: redis://redis:6379/0

general:
  debug: false
  instance_name:  "SawyerSearch"
  privacypolicy_url: false
  contact_url: false
  enable_metrics: false
  donation_url: false

search:
  safe_search: 0
  autocomplete: "duckduckgo"
  default_lang: ""
  ban_time_on_fail: 5
  max_ban_time_on_fail: 120
  formats:
    - html

categories_as_tabs:
  general:
  images:
  videos:
  news:
  map:
  music:
  it:
  science:
  files:
  social media:

engines:
  - name: arch linux wiki
    engine: archlinux
    shortcut: al

  - name: archive is
    engine: xpath
    search_url: https://archive.is/search/?q={query}
    url_xpath: (//div[@class="TEXT-BLOCK"]/a)/@href
    title_xpath: (//div[@class="TEXT-BLOCK"]/a)
    content_xpath: //div[@class="TEXT-BLOCK"]/ul/li
    categories: general
    timeout: 7.0
    disabled: true
    shortcut: ai
    soft_max_redirects: 1
    about:
      website: https://archive.is/
      wikidata_id: Q13515725
      official_api_documentation: https://mementoweb.org/depot/native/archiveis/
      use_official_api: false
      require_api_key: false
      results: HTML

  - name: wikipedia
    engine: wikipedia
    shortcut: wp
    base_url: 'https://{language}.wikipedia.org/'

  - name: bing
    engine: bing
    shortcut: bi
    disabled: true

  - name: bing images
    engine: bing_images
    shortcut: bii

  - name: bing news
    engine: bing_news
    shortcut: bin

  - name: bing videos
    engine: bing_videos
    shortcut: biv

  - name: bitbucket
    engine: xpath
    paging: true
    search_url: https://bitbucket.org/repo/all/{pageno}?name={query}
    url_xpath: //article[@class="repo-summary"]//a[@class="repo-link"]/@href
    title_xpath: //article[@class="repo-summary"]//a[@class="repo-link"]
    content_xpath: //article[@class="repo-summary"]/p
    categories: [it, repos]
    timeout: 4.0
    disabled: true
    shortcut: bb
    about:
      website: https://bitbucket.org/
      wikidata_id: Q2493781
      official_api_documentation: https://developer.atlassian.com/bitbucket
      use_official_api: false
      require_api_key: false
      results: HTML

  - name: openverse
    engine: openverse
    categories: images
    shortcut: opv

  - name: crossref
    engine: json_engine
    paging: true
    search_url: https://search.crossref.org/dois?q={query}&page={pageno}
    url_query: doi
    title_query: title
    title_html_to_text: true
    content_query: fullCitation
    content_html_to_text: true
    categories: science
    shortcut: cr
    about:
      website: https://www.crossref.org/
      wikidata_id: Q5188229
      official_api_documentation: https://github.com/CrossRef/rest-api-doc
      use_official_api: false
      require_api_key: false
      results: JSON

  - name: yep
    engine: json_engine
    shortcut: yep
    categories: general
    disabled: true
    paging: false
    content_html_to_text: true
    title_html_to_text: true
    search_url: https://api.yep.com/fs/1/?type=web&q={query}&no_correct=false&limit=100
    results_query: 1/results
    title_query: title
    url_query: url
    content_query: snippet
    about:
      website: https://yep.com
      use_official_api: false
      require_api_key: false
      results: JSON

  - name: curlie
    engine: xpath
    shortcut: cl
    categories: general
    disabled: true
    paging: true
    lang_all: ''
    search_url: https://curlie.org/search?q={query}&lang={lang}&start={pageno}&stime=92452189
    page_size: 20
    results_xpath: //div[@id="site-list-content"]/div[@class="site-item"]
    url_xpath: ./div[@class="title-and-desc"]/a/@href
    title_xpath: ./div[@class="title-and-desc"]/a/div
    content_xpath: ./div[@class="title-and-desc"]/div[@class="site-descr"]
    about:
      website: https://curlie.org/
      wikidata_id: Q60715723
      use_official_api: false
      require_api_key: false
      results: HTML

  - name: currency
    engine: currency_convert
    categories: general
    shortcut: cc

  - name: deezer
    engine: deezer
    shortcut: dz
    disabled: true

  - name: deviantart
    engine: deviantart
    shortcut: da
    timeout: 3.0

  - name: ddg definitions
    engine: duckduckgo_definitions
    shortcut: ddd
    weight: 2
    disabled: true

  # cloudflare protected
  # - name: digbt
  #   engine: digbt
  #   shortcut: dbt
  #   timeout: 6.0
  #   disabled: true

  - name: docker hub
    engine: docker_hub
    shortcut: dh
    categories: [it, packages]

  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg

  - name: duckduckgo images
    engine: duckduckgo_images
    shortcut: ddi
    timeout: 3.0
    disabled: true

  - name: tineye
    engine: tineye
    shortcut: tin
    timeout: 9.0

  - name: fdroid
    engine: fdroid
    shortcut: fd
    disabled: true

  - name: free software directory
    engine: mediawiki
    shortcut: fsd
    categories: [it, software wikis]
    base_url: https://directory.fsf.org/
    number_of_results: 5
    # what part of a page matches the query string: title, text, nearmatch
    # * title     - query matches title
    # * text      - query matches the text of page
    # * nearmatch - nearmatch in title
    search_type: title
    timeout: 5.0
    disabled: true
    about:
      website: https://directory.fsf.org/
      wikidata_id: Q2470288

  - name: gitlab
    engine: json_engine
    paging: true
    search_url: https://gitlab.com/api/v4/projects?search={query}&page={pageno}
    url_query: web_url
    title_query: name_with_namespace
    content_query: description
    page_size: 20
    categories: [it, repos]
    shortcut: gl
    timeout: 10.0
    disabled: true
    about:
      website: https://about.gitlab.com/
      wikidata_id: Q16639197
      official_api_documentation: https://docs.gitlab.com/ee/api/
      use_official_api: false
      require_api_key: false
      results: JSON

  - name: github
    engine: github
    shortcut: gh

  - name: google
    engine: google
    shortcut: go
    # see https://docs.searxng.org/src/searx.engines.google.html#module-searx.engines.google
    use_mobile_ui: false
    # additional_tests:
    #   android: *test_android

  # - name: google italian
  #   engine: google
  #   shortcut: goit
  #   use_mobile_ui: false
  #   language: it

  # - name: google mobile ui
  #   engine: google
  #   shortcut: gomui
  #   use_mobile_ui: true

  - name: google images
    engine: google_images
    shortcut: goi
    # additional_tests:
    #   android: *test_android
    #   dali:
    #     matrix:
    #       query: ['Dali Christ']
    #       lang: ['en', 'de', 'fr', 'zh-CN']
    #     result_container:
    #       - ['one_title_contains', 'Salvador']

  - name: google news
    engine: google_news
    shortcut: gon
    # additional_tests:
    #   android: *test_android

  - name: google videos
    engine: google_videos
    shortcut: gov
    # additional_tests:
    #   android: *test_android

  - name: google scholar
    engine: google_scholar
    shortcut: gos

  - name: google play apps
    engine: google_play_apps
    shortcut: gpa
    disabled: true

  - name: google play movies
    engine: xpath
    send_accept_language_header: true
    search_url: https://play.google.com/store/search?q={query}&c=movies
    results_xpath: '//div[@class="ImZGtf mpg5gc"]'
    title_xpath: './/div[@class="RZEgze"]//div[@class="kCSSQe"]//a'
    url_xpath: './/div[@class="RZEgze"]//div[@class="kCSSQe"]//a/@href'
    content_xpath: './/div[@class="kCSSQe"]'
    thumbnail_xpath: './/div[@class="uzcko"]/div/span[1]//img/@data-src'
    categories: videos
    shortcut: gpm
    disabled: true
    about:
      website: https://play.google.com/
      wikidata_id: Q79576
      official_api_documentation:
      use_official_api: false
      require_api_key: false
      results: HTML

  - name: hoogle
    engine: xpath
    paging: true
    search_url: https://hoogle.haskell.org/?hoogle={query}&start={pageno}
    results_xpath: '//div[@class="result"]'
    title_xpath: './/div[@class="ans"]//a'
    url_xpath: './/div[@class="ans"]//a/@href'
    content_xpath: './/div[@class="from"]'
    page_size: 20
    categories: [it, packages]
    shortcut: ho
    about:
      website: https://hoogle.haskell.org/
      wikidata_id: Q34010
      official_api_documentation: https://hackage.haskell.org/api
      use_official_api: false
      require_api_key: false
      results: JSON

  - name: imdb
    engine: imdb
    shortcut: imdb
    timeout: 6.0
    disabled: true

  - name: invidious
    engine: invidious
    # Instanes will be selected randomly, see https://api.invidious.io/ for
    # instances that are stable (good uptime) and close to you.
    base_url:
      - https://invidious.snopyta.org
      - https://vid.puffyan.us
      # - https://invidious.kavin.rocks  # Error 1020 // Access denied by Cloudflare
      - https://invidio.xamh.de
      - https://inv.riverside.rocks
    shortcut: iv
    timeout: 3.0
    disabled: true

  - name: library of congress
    engine: loc
    shortcut: loc
    categories: images

  - name: npm
    engine: json_engine
    paging: true
    first_page_num: 0
    search_url: https://api.npms.io/v2/search?q={query}&size=25&from={pageno}
    results_query: results
    url_query: package/links/npm
    title_query: package/name
    content_query: package/description
    page_size: 25
    categories: [it, packages]
    disabled: true
    timeout: 5.0
    shortcut: npm
    about:
      website: https://npms.io/
      wikidata_id: Q7067518
      official_api_documentation: https://api-docs.npms.io/
      use_official_api: false
      require_api_key: false
      results: JSON

  - name: openairepublications
    engine: json_engine
    paging: true
    search_url: https://api.openaire.eu/search/publications?format=json&page={pageno}&size=10&title={query}
    results_query: response/results/result
    url_query: metadata/oaf:entity/oaf:result/children/instance/webresource/url/$
    title_query: metadata/oaf:entity/oaf:result/title/$
    content_query: metadata/oaf:entity/oaf:result/description/$
    content_html_to_text: true
    categories: science
    shortcut: oap
    timeout: 5.0
    about:
      website: https://www.openaire.eu/
      wikidata_id: Q25106053
      official_api_documentation: https://api.openaire.eu/
      use_official_api: false
      require_api_key: false
      results: JSON

  # - name: opensemanticsearch
  #   engine: opensemantic
  #   shortcut: oss
  #   base_url: 'http://localhost:8983/solr/opensemanticsearch/'

  - name: openstreetmap
    engine: openstreetmap
    shortcut: osm

  - name: openrepos
    engine: xpath
    paging: true
    search_url: https://openrepos.net/search/node/{query}?page={pageno}
    url_xpath: //li[@class="search-result"]//h3[@class="title"]/a/@href
    title_xpath: //li[@class="search-result"]//h3[@class="title"]/a
    content_xpath: //li[@class="search-result"]//div[@class="search-snippet-info"]//p[@class="search-snippet"]
    categories: files
    timeout: 4.0
    disabled: true
    shortcut: or
    about:
      website: https://openrepos.net/
      wikidata_id:
      official_api_documentation:
      use_official_api: false
      require_api_key: false
      results: HTML

  - name: piratebay
    engine: piratebay
    shortcut: tpb
    # You may need to change this URL to a proxy if piratebay is blocked in your
    # country
    url: https://thepiratebay.org/
    timeout: 3.0

  - name: pypi
    shortcut: pypi
    engine: xpath
    paging: true
    search_url: https://pypi.org/search?q={query}&page={pageno}
    results_xpath: /html/body/main/div/div/div/form/div/ul/li/a[@class="package-snippet"]
    url_xpath: ./@href
    title_xpath: ./h3/span[@class="package-snippet__name"]
    content_xpath: ./p
    suggestion_xpath: /html/body/main/div/div/div/form/div/div[@class="callout-block"]/p/span/a[@class="link"]
    first_page_num: 1
    categories: [it, packages]
    about:
      website: https://pypi.org
      wikidata_id: Q2984686
      official_api_documentation: https://warehouse.readthedocs.io/api-reference/index.html
      use_official_api: false
      require_api_key: false
      results: HTML

  - name: qwant
    qwant_categ: web
    engine: qwant
    shortcut: qw
    categories: [general, web]
    disabled: false

  - name: qwant news
    qwant_categ: news
    engine: qwant
    shortcut: qwn
    categories: news
    disabled: false
    network: qwant

  - name: qwant images
    qwant_categ: images
    engine: qwant
    shortcut: qwi
    categories: [images, web]
    disabled: false
    network: qwant

  - name: qwant videos
    qwant_categ: videos
    engine: qwant
    shortcut: qwv
    categories: [videos, web]
    disabled: false
    network: qwant

  - name: reddit
    engine: reddit
    shortcut: re
    page_size: 25

  - name: stackoverflow
    engine: stackexchange
    shortcut: st
    api_site: 'stackoverflow'
    categories: [it, q&a]

  - name: askubuntu
    engine: stackexchange
    shortcut: ubuntu
    api_site: 'askubuntu'
    categories: [it, q&a]

  - name: superuser
    engine: stackexchange
    shortcut: su
    api_site: 'superuser'
    categories: [it, q&a]

  - name: semantic scholar
    engine: semantic_scholar
    disabled: true
    shortcut: se
    categories: science

  - name: solidtorrents
    engine: solidtorrents
    shortcut: solid
    timeout: 4.0
    disabled: false
    base_url:
      - https://solidtorrents.net
      - https://solidtorrents.eu
      - https://solidtorrents.to
      - https://bitsearch.to

  - name: unsplash
    engine: unsplash
    shortcut: us

  - name: yahoo
    engine: yahoo
    shortcut: yh
    disabled: true

  - name: yahoo news
    engine: yahoo_news
    shortcut: yhn

  - name: youtube
    shortcut: yt
    # You can use the engine using the official stable API, but you need an API
    # key See: https://console.developers.google.com/project
    #
    # engine: youtube_api
    # api_key: 'apikey' # required!
    #
    # Or you can use the html non-stable engine, activated by default
    engine: youtube_noapi

  - name: wikibooks
    engine: mediawiki
    shortcut: wb
    categories: general
    base_url: "https://{language}.wikibooks.org/"
    number_of_results: 5
    search_type: text
    disabled: true
    about:
      website: https://www.wikibooks.org/
      wikidata_id: Q367

  - name: wikinews
    engine: mediawiki
    shortcut: wn
    categories: news
    base_url: "https://{language}.wikinews.org/"
    number_of_results: 5
    search_type: text
    disabled: true
    about:
      website: https://www.wikinews.org/
      wikidata_id: Q964

  - name: wikiquote
    engine: mediawiki
    shortcut: wq
    categories: general
    base_url: "https://{language}.wikiquote.org/"
    number_of_results: 5
    search_type: text
    disabled: true
    about:
      website: https://www.wikiquote.org/
      wikidata_id: Q369

  - name: wikisource
    engine: mediawiki
    shortcut: ws
    categories: general
    base_url: "https://{language}.wikisource.org/"
    number_of_results: 5
    search_type: text
    disabled: true
    about:
      website: https://www.wikisource.org/
      wikidata_id: Q263

  - name: wiktionary
    engine: mediawiki
    shortcut: wt
    categories: [dictionaries]
    base_url: "https://{language}.wiktionary.org/"
    number_of_results: 5
    search_type: text
    disabled: false
    about:
      website: https://www.wiktionary.org/
      wikidata_id: Q151

  - name: wikiversity
    engine: mediawiki
    shortcut: wv
    categories: general
    base_url: "https://{language}.wikiversity.org/"
    number_of_results: 5
    search_type: text
    disabled: true
    about:
      website: https://www.wikiversity.org/
      wikidata_id: Q370

  - name: wikivoyage
    engine: mediawiki
    shortcut: wy
    categories: general
    base_url: "https://{language}.wikivoyage.org/"
    number_of_results: 5
    search_type: text
    disabled: true
    about:
      website: https://www.wikivoyage.org/
      wikidata_id: Q373

  - name: brave
    shortcut: brave
    engine: xpath
    paging: true
    time_range_support: true
    first_page_num: 0
    time_range_url: "&tf={time_range_val}"
    search_url: https://search.brave.com/search?q={query}&offset={pageno}&spellcheck=1{time_range}
    url_xpath: //a[@class="result-header"]/@href
    title_xpath: //span[@class="snippet-title"]
    content_xpath: //p[1][@class="snippet-description"]
    suggestion_xpath: //div[@class="text-gray h6"]/a
    time_range_map:
      day: 'pd'
      week: 'pw'
      month: 'pm'
      year: 'py'
    categories: [general, web]
    disabled: true
    about:
      website: https://brave.com/search/
      wikidata_id: Q107355971
      use_official_api: false
      require_api_key: false
      results: HTML

  - name: petalsearch
    shortcut: pts
    engine: xpath
    paging: true
    search_url: https://petalsearch.com/search?query={query}&pn={pageno}
    results_xpath: //div[@class="webpage-content"]/div[@class="title-cont"]/a
    url_xpath: ./@href
    title_xpath: .
    content_xpath: ../../div[@class="webpage-text"]
    suggestion_xpath: //div[@class="related-search-items"]/a
    first_page_num: 1
    disabled: true
    about:
      website: https://petalsearch.com/
      wikidata_id: Q104399280
      use_official_api: false
      require_api_key: false
      results: HTML

  - name: petalsearch images
    engine: petal_images
    shortcut: ptsi
    disabled: true
    timeout: 3.0

  - name: petalsearch news
    shortcut: ptsn
    categories: news
    engine: xpath
    paging: true
    search_url: https://petalsearch.com/search?channel=news&query={query}&pn={pageno}
    results_xpath: //div[@class="news-container"]/div/div/div/a
    url_xpath: ./@href
    title_xpath: ./div
    content_xpath: ../div[@class="news-text"]
    thumbnail_xpath: ../../../../img/@src
    first_page_num: 1
    disabled: true
    about:
      website: https://petalsearch.com/
      wikidata_id: Q104399280
      use_official_api: false
      require_api_key: false
      results: HTML

  - name: sourcehut
    shortcut: srht
    engine: xpath
    paging: true
    search_url: https://sr.ht/projects?page={pageno}&search={query}
    results_xpath: (//div[@class="event-list"])[1]/div[@class="event"]
    url_xpath: ./h4/a[2]/@href
    title_xpath: ./h4/a[2]
    content_xpath: ./p
    first_page_num: 1
    categories: [it, repos]
    disabled: true
    about:
      website: https://sr.ht
      wikidata_id: Q78514485
      official_api_documentation: https://man.sr.ht/
      use_official_api: false
      require_api_key: false
      results: HTML
doi_resolvers:
  oadoi.org: 'https://oadoi.org/'
  doi.org: 'https://doi.org/'
  doai.io: 'https://dissem.in/'
  sci-hub.se: 'https://sci-hub.se/'
  sci-hub.do: 'https://sci-hub.do/'
  scihubtw.tw: 'https://scihubtw.tw/'
  sci-hub.st: 'https://sci-hub.st/'
  sci-hub.bar: 'https://sci-hub.bar/'
  sci-hub.it.nf: 'https://sci-hub.it.nf/'
